apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
kubernetesVersion: stable
apiServer:
  certSANs:
  - "172.27.127.175"
controlPlaneEndpoint: "172.27.127.175:6443"
etcd:
    external:
        endpoints:
        - https://172.27.127.194:2379
        - https://172.27.127.198:2379
        - https://172.27.127.203:2379
        caFile: /etc/kubernetes/pki/etcd/ca.crt
        certFile: /etc/kubernetes/pki/apiserver-etcd-client.crt
        keyFile: /etc/kubernetes/pki/apiserver-etcd-client.key
networking:
  podSubnet: 10.244.0.0/16

